version: "3.2"

services:
  server:
    image: brzserver/ragemp
    depends_on:
      - mysql
    ports:
      - target: 22005
        published: 22005
        protocol: udp
        mode: host
      - 22006:22006
    volumes:
      - /data/ragemp:/ragemp
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.hostname == samp-rpgmgs
    networks:
      - ragemp
      - proxy

  mysql:
    image: mysql:5.6
    volumes:
        - /data/ragempdb:/var/lib/mysql
    ports:
      - 33010:3306
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
      MYSQL_DATABASE: BRAZUCAS
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.hostname == samp-rpgmgs
    networks:
      - ragemp
      - proxy

networks:
  ragemp:
  proxy:
    external: true
