# docker-compose used for the dev environment

version: "3.2"

services:
  ragemp_server:
    image: brzserver/ragemp
    depends_on:
      - ragemp_mysql
    ports:
      - target: 22005
        published: 22005
        protocol: udp
        mode: host
      - 22006:22006
    volumes:
      - ./:/ragemp
    networks:
      - ragemp

  ragemp_mysql:
    image: mysql:5.6
    volumes:
      - ../ragemp-data/mysql:/var/lib/mysql
    ports:
      - 33010:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: BRAZUCAS
    networks:
      - ragemp

networks:
  ragemp:
    driver: bridge
